name: core_logging
description: package for logging app errors and information
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

# Configure for Dart Workspace resolution
resolution: workspace

dependencies:
  adaptive_dialog: ^2.1.0
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  fpdart: ^1.1.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: 7.2.0
  injectable: ^2.4.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  logger: ^2.3.0
  path_provider: ^2.1.3

dev_dependencies:
  core_analysis: any
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
