name: navigation
description: navigation package for starter_app
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  app_logging:
    path: ../../core/app_logging
  app_theme:
    path: ../../core/app_theme
  contact:
    path: ../../features/contact
  dashboard:
    path: ../../features/dashboard
  flutter:
    sdk: flutter
  get_it: 7.2.0
  go_router: ^14.2.8
  team:
    path: ../../features/team

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
