name: navigation
description: navigation package for starter_app
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

# Configure for Dart Workspace resolution
resolution: workspace

dependencies:
  login_signup: any
  core_authentication: any
  core_logging: any
  core_theme: any
  contact: any
  dashboard: any
  flutter:
    sdk: flutter
  get_it: 7.2.0
  go_router: ^14.2.8
  munro_list: any
  offline: any
  team: any
  settings: any
  async: ^2.11.0

dev_dependencies:
  core_analysis: any
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
