name: navigation
description: navigation package for starter_app
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  login_signup:
    path: ../../features/login_signup
  core_authentication:
    path: ../../core/core_authentication
  core_logging:
    path: ../../core/core_logging
  core_theme:
    path: ../../core/core_theme
  contact:
    path: ../../features/contact
  dashboard:
    path: ../../features/dashboard
  flutter:
    sdk: flutter
  get_it: 7.2.0
  go_router: ^14.2.8
  munro_list:
    path: ../../features/munro_list
  offline:
    path: ../../features/offline
  team:
    path: ../../features/team
  settings:
    path: ../../features/settings
  async: ^2.11.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
