name: starter_app

packages:
  - packages/**

command:
  bootstrap:
    environment:
      sdk: ^3.5.0
    dependencies:
      flow_builder: ^0.1.0
      flutter:
        sdk: flutter
      flutter_bloc: ^8.1.5
      fpdart: ^1.1.0
      freezed: ^2.5.2
      freezed_annotation: ^2.4.1
      get_it: 7.2.0
      injectable: ^2.4.2
      lego_architecture_demo_mason:
        path: ../../app/starter_app
    dev_dependencies:
      build_runner: ^2.4.9
      flutter_test:
        sdk: flutter
      injectable_generator: ^2.6.1
      mocktail: ^1.0.4
      very_good_analysis: ^6.0.0

scripts:
  analyze:
    exec: dart analyze .

  generate:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
