name: offline
description: handles the apps offline state
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  connectivity_plus: ^6.0.5
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  fpdart: ^1.1.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: 7.2.0
  injectable: ^2.4.2
  lego_architecture_demo_mason:
    path: ../../app/starter_app

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
