name: core_prelude
description: Foundation components
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dev_dependencies:
  core_analysis: any
  flutter_test:
    sdk: flutter
  test: ^1.25.15
