name: core_analytics
description: a package to handle app analytics
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

# Configure for Dart Workspace resolution
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  core_analysis: any
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
