name: settings
description: The settings page for the app
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  core_theme:
    path: ../../core/core_theme
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: 7.2.0
  injectable: ^2.4.2
  lego_architecture_demo_mason:
    path: ../../app/starter_app

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
