name: starter_app
description: Demo project for package based architecute
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

# Configure for Dart Workspace resolution
resolution: workspace

dependencies:
  bloc: ^8.1.4
  core_authentication: any
  core_logging: any
  core_theme: any
  core_munros_data: any
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  get_it: 7.2.0
  intl: ^0.18.0
  navigation: any
  offline: any
  i69n: any

dev_dependencies:
  core_analysis: any
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
