name: munro_list
description: The list of all munros
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

# Configure for Dart Workspace resolution
resolution: workspace

dependencies:
  core_munros_data: any
  csv: ^6.0.0
  drift: 2.19.1+1
  drift_flutter: 0.1.0
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: 7.2.0
  injectable: ^2.4.2
  starter_app: any

dev_dependencies:
  core_analysis: any
  build_runner: ^2.4.9
  drift_dev: 2.19.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
